services:
  angular:
    container_name: angular
    build:
      context: ../frontend
    volumes:
      - ../frontend:/usr/src/app
    ports:
      - 4200:4200
    command: ["sh", "./start.sh"]

  nodejs:
    container_name: nodejs
    build: 
      context: ../backend
    volumes: 
      - ../backend:/usr/src/app
    ports:
      - 3000:3000
    command: ["sh", "./start.sh", "bdd"]
    
  bdd:
    container_name: bdd
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - 4000:4000